const posts = [
    {
    type_of: "article",
    id: 1093019,
    title: "Do you remember the FIRST project made by you?",
    description: "Do you remember the very first project made by you when you started learning to code in a particular...",
    readable_publish_date: "May 23",
    slug: "do-you-remember-the-first-project-made-by-you-2ap8",
    path: "/asheeshh/do-you-remember-the-first-project-made-by-you-2ap8",
    url: "https://dev.to/asheeshh/do-you-remember-the-first-project-made-by-you-2ap8",
    comments_count: 50,
    public_reactions_count: 25,
    collection_id: null,
    published_timestamp: "2022-05-23T01:29:16Z",
    positive_reactions_count: 25,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1093019.png",
    canonical_url: "https://dev.to/asheeshh/do-you-remember-the-first-project-made-by-you-2ap8",
    created_at: "2022-05-23T01:29:16Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-23T01:29:16Z",
    last_comment_at: "2022-05-23T14:22:44Z",
    reading_time_minutes: 1,
    tag_list: [
    "discuss",
    "showdev",
    "webdev",
    "programming"
    ],
    tags: "discuss, showdev, webdev, programming",
    user: {
    name: "ashish ",
    username: "asheeshh",
    twitter_username: "_asheeshh",
    github_username: "asheeeshh",
    website_url: "https://ayyy.asheeshh.ninja/",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--bRe1ovgr--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/720342/d472fb52-fe88-4396-bcf8-bf5d14fd1db7.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--dmiqnmxu--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/720342/d472fb52-fe88-4396-bcf8-bf5d14fd1db7.png"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1093406,
    title: "⛔ Squash commits considered harmful ⛔",
    description: "A recurring conversation in developer circles is if you should use git --squash when merging or do...",
    readable_publish_date: "May 23",
    slug: "squash-commits-considered-harmful-ob1",
    path: "/wesen/squash-commits-considered-harmful-ob1",
    url: "https://dev.to/wesen/squash-commits-considered-harmful-ob1",
    comments_count: 14,
    public_reactions_count: 15,
    collection_id: null,
    published_timestamp: "2022-05-23T11:46:32Z",
    positive_reactions_count: 15,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--vTKTjPSd--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/bnr8zi5a3btotaeddvon.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--sS9yhD7---/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/bnr8zi5a3btotaeddvon.png",
    canonical_url: "https://dev.to/wesen/squash-commits-considered-harmful-ob1",
    created_at: "2022-05-23T11:45:05Z",
    edited_at: "2022-05-23T14:12:38Z",
    crossposted_at: null,
    published_at: "2022-05-23T11:46:32Z",
    last_comment_at: "2022-05-23T15:02:08Z",
    reading_time_minutes: 7,
    tag_list: [
    "programming",
    "productivity",
    "tutorial",
    "git"
    ],
    tags: "programming, productivity, tutorial, git",
    user: {
    name: "Manuel Odendahl",
    username: "wesen",
    twitter_username: "mnmlmnl",
    github_username: "wesen",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--rVauy25G--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/852108/c4c6139f-b639-4642-bc3a-0e984d97c5ca.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--Kd79In6k--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/852108/c4c6139f-b639-4642-bc3a-0e984d97c5ca.jpeg"
    }
    },
    {
    type_of: "article",
    id: 1093343,
    title: "Which Frontend Framework Would You Use For an Ecommerce Storefront?",
    description: "Medusa provides 2 starter storefronts for your headless commerce platform, one using Next.js and one...",
    readable_publish_date: "May 23",
    slug: "which-frontend-framework-would-you-use-for-an-ecommerce-storefront-3apg",
    path: "/medusajs/which-frontend-framework-would-you-use-for-an-ecommerce-storefront-3apg",
    url: "https://dev.to/medusajs/which-frontend-framework-would-you-use-for-an-ecommerce-storefront-3apg",
    comments_count: 12,
    public_reactions_count: 12,
    collection_id: null,
    published_timestamp: "2022-05-23T09:49:05Z",
    positive_reactions_count: 12,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--HrLzKNoY--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/7s4xd1a15fs8m6dlngfn.jpg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--b1MwVvT---/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/7s4xd1a15fs8m6dlngfn.jpg",
    canonical_url: "https://dev.to/medusajs/which-frontend-framework-would-you-use-for-an-ecommerce-storefront-3apg",
    created_at: "2022-05-23T09:49:05Z",
    edited_at: "2022-05-23T09:49:16Z",
    crossposted_at: null,
    published_at: "2022-05-23T09:49:05Z",
    last_comment_at: "2022-05-23T14:54:44Z",
    reading_time_minutes: 1,
    tag_list: [
    "discuss",
    "javascript",
    "webdev",
    "opensource"
    ],
    tags: "discuss, javascript, webdev, opensource",
    user: {
    name: "Shahed Nasser",
    username: "shahednasser",
    twitter_username: "shahednasser95",
    github_username: "shahednasser",
    website_url: "https://blog.shahednasser.com",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--FTNUcJld--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/507096/4c4fb7e8-95c7-4093-8ebd-2d8c92bec743.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--iPKuTay6--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/507096/4c4fb7e8-95c7-4093-8ebd-2d8c92bec743.jpg"
    },
    organization: {
    name: "Medusa",
    username: "medusajs",
    slug: "medusajs",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--Os_3zx1y--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/4507/a2eb0df7-8e79-4f4a-8b04-c9acc41f91f9.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--vd0MzrGZ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/4507/a2eb0df7-8e79-4f4a-8b04-c9acc41f91f9.jpg"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1092564,
    title: "As a developer, I hate ... ?",
    description: "In your career as a developer, what are the main three things that you hate about being in the tech...",
    readable_publish_date: "May 22",
    slug: "as-a-developer-i-hate--3g2e",
    path: "/bekbrace/as-a-developer-i-hate--3g2e",
    url: "https://dev.to/bekbrace/as-a-developer-i-hate--3g2e",
    comments_count: 103,
    public_reactions_count: 39,
    collection_id: null,
    published_timestamp: "2022-05-22T09:54:49Z",
    positive_reactions_count: 39,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--FCf6OelP--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/xu037gv870tiubwb1lb9.jpg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--kFbErd6C--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/xu037gv870tiubwb1lb9.jpg",
    canonical_url: "https://dev.to/bekbrace/as-a-developer-i-hate--3g2e",
    created_at: "2022-05-22T09:54:29Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-22T09:54:49Z",
    last_comment_at: "2022-05-23T14:56:24Z",
    reading_time_minutes: 1,
    tag_list: [
    "discuss",
    "career",
    "webdev",
    "watercooler"
    ],
    tags: "discuss, career, webdev, watercooler",
    user: {
    name: "Bek Brace",
    username: "bekbrace",
    twitter_username: "BekBrace",
    github_username: "BekBrace",
    website_url: "https://bekbrace.com",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--Kuik89ne--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/351271/455d1d65-9738-4ca4-b7a7-7d959f79eab1.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--8TVSy8Hh--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/351271/455d1d65-9738-4ca4-b7a7-7d959f79eab1.png"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1093618,
    title: "Music Monday — What are you listening to? (May 23)",
    description: "cover image credits: Jimmy Arca In this weekly series, folks can chime in and drop links to whatever...",
    readable_publish_date: "May 23",
    slug: "music-monday-what-are-you-listening-to-may-23-104p",
    path: "/music-discussions/music-monday-what-are-you-listening-to-may-23-104p",
    url: "https://dev.to/music-discussions/music-monday-what-are-you-listening-to-may-23-104p",
    comments_count: 2,
    public_reactions_count: 8,
    collection_id: 17887,
    published_timestamp: "2022-05-23T14:16:59Z",
    positive_reactions_count: 8,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--V7CXyS7k--/c_imagga_scale,f_auto,fl_progressive,h_420,q_66,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/az2lp6kxmtrf4oeliw2t.gif",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--ZHCKu4Kd--/c_imagga_scale,f_auto,fl_progressive,h_500,q_66,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/az2lp6kxmtrf4oeliw2t.gif",
    canonical_url: "https://dev.to/music-discussions/music-monday-what-are-you-listening-to-may-23-104p",
    created_at: "2022-05-23T14:16:59Z",
    edited_at: "2022-05-23T14:36:17Z",
    crossposted_at: null,
    published_at: "2022-05-23T14:16:59Z",
    last_comment_at: "2022-05-23T14:59:48Z",
    reading_time_minutes: 1,
    tag_list: [
    "watercooler",
    "discuss",
    "music"
    ],
    tags: "watercooler, discuss, music",
    user: {
    name: "Michael Tharrington (he/him)",
    username: "michaeltharrington",
    twitter_username: "MichaelMadcat",
    github_username: "michael-tharrington",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--FghtiDVB--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/38578/2b719be8-68c7-4456-bd5c-42f21c3bd6a8.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--fySxNi_p--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/38578/2b719be8-68c7-4456-bd5c-42f21c3bd6a8.png"
    },
    organization: {
    name: "#music discussions",
    username: "music-discussions",
    slug: "music-discussions",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--DlrFWObY--/c_fill,f_auto,fl_progressive,h_640,q_66,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/5579/2ecc2b3c-301f-4eb6-82f8-dabf0e455df2.gif",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--aDo-bgN7--/c_fill,f_auto,fl_progressive,h_90,q_66,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/5579/2ecc2b3c-301f-4eb6-82f8-dabf0e455df2.gif"
    },
    flare_tag: {
    name: "watercooler",
    bg_color_hex: "#D0ECFF",
    text_color_hex: "#130074"
    }
    },
    {
    type_of: "article",
    id: 1087446,
    title: "A Guide to writing Industry Standard Git Commit Message",
    description: "I bet you already heard something about Git before starting this article whatever led you here,...",
    readable_publish_date: "May 23",
    slug: "a-guide-to-writing-industry-standard-git-commit-message-2ohl",
    path: "/tuasegun/a-guide-to-writing-industry-standard-git-commit-message-2ohl",
    url: "https://dev.to/tuasegun/a-guide-to-writing-industry-standard-git-commit-message-2ohl",
    comments_count: 0,
    public_reactions_count: 10,
    collection_id: null,
    published_timestamp: "2022-05-23T14:14:32Z",
    positive_reactions_count: 10,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--DXBzIEO6--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/c0bnyxbi7voh1yba0ixb.jpeg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--jRJ1qdTy--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/c0bnyxbi7voh1yba0ixb.jpeg",
    canonical_url: "https://dev.to/tuasegun/a-guide-to-writing-industry-standard-git-commit-message-2ohl",
    created_at: "2022-05-17T01:17:43Z",
    edited_at: "2022-05-23T14:14:54Z",
    crossposted_at: null,
    published_at: "2022-05-23T14:14:32Z",
    last_comment_at: "2022-05-23T14:14:32Z",
    reading_time_minutes: 3,
    tag_list: [
    "git",
    "github",
    "programming",
    "opensource"
    ],
    tags: "git, github, programming, opensource",
    user: {
    name: "Tuasegun",
    username: "tuasegun",
    twitter_username: null,
    github_username: "Tuasegun",
    website_url: "https://github.com/tuasegun",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--_IquXHGt--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/686931/74a4a911-1ea7-48f0-a8b6-42306aa4a2cd.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--Gq0eEoSw--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/686931/74a4a911-1ea7-48f0-a8b6-42306aa4a2cd.jpeg"
    }
    },
    {
    type_of: "article",
    id: 1004172,
    title: "Git branching for small teams",
    description: "Here’s a practice I use personally and encourage within my open source projects and any small...",
    readable_publish_date: "May 23",
    slug: "git-branching-for-small-teams-2n64",
    path: "/victoria/git-branching-for-small-teams-2n64",
    url: "https://dev.to/victoria/git-branching-for-small-teams-2n64",
    comments_count: 5,
    public_reactions_count: 11,
    collection_id: null,
    published_timestamp: "2022-05-23T12:13:05Z",
    positive_reactions_count: 11,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--ZIDMmH_1--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/1sfhpybll82vpgf3gly6.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--erzQT5Os--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/1sfhpybll82vpgf3gly6.png",
    canonical_url: "https://victoria.dev/blog/git-branching-for-small-teams/",
    created_at: "2022-02-28T15:23:28Z",
    edited_at: "2022-05-23T12:14:43Z",
    crossposted_at: "2022-05-23T12:13:05Z",
    published_at: "2022-05-23T12:12:48Z",
    last_comment_at: "2022-05-23T14:51:30Z",
    reading_time_minutes: 3,
    tag_list: [
    "productivity",
    "git",
    "startup"
    ],
    tags: "productivity, git, startup",
    user: {
    name: "Victoria Drake",
    username: "victoria",
    twitter_username: "victoriadotdev",
    github_username: "victoriadrake",
    website_url: "https://victoria.dev",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--X7k01B3x--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/19058/a14d3d05-bdd3-43b3-b747-4306e68b132c.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--SucFuP3Q--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/19058/a14d3d05-bdd3-43b3-b747-4306e68b132c.jpeg"
    }
    },
    {
    type_of: "article",
    id: 1087007,
    title: "📚 Redux Toolkit Setup Tutorial",
    description: "Introduction Does anyone feel reluctant when you want to implement Redux in your react...",
    readable_publish_date: "May 23",
    slug: "redux-toolkit-setup-tutorial-5fjf",
    path: "/raaynaldo/redux-toolkit-setup-tutorial-5fjf",
    url: "https://dev.to/raaynaldo/redux-toolkit-setup-tutorial-5fjf",
    comments_count: 0,
    public_reactions_count: 9,
    collection_id: null,
    published_timestamp: "2022-05-23T13:42:05Z",
    positive_reactions_count: 9,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--_KooT61---/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/uipwnt3jh5gcnmhnlq91.jpg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--uSja6sJj--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/uipwnt3jh5gcnmhnlq91.jpg",
    canonical_url: "https://dev.to/raaynaldo/redux-toolkit-setup-tutorial-5fjf",
    created_at: "2022-05-16T13:17:23Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-23T13:42:05Z",
    last_comment_at: "2022-05-23T13:42:05Z",
    reading_time_minutes: 5,
    tag_list: [
    "redux",
    "react",
    "javascript",
    "tutorial"
    ],
    tags: "redux, react, javascript, tutorial",
    user: {
    name: "Raynaldo Sutisna",
    username: "raaynaldo",
    twitter_username: "raaynaldo",
    github_username: "raaynaldo",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--5ZKiM82b--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/494666/669a1cb1-b348-47fd-aebe-297bb66d2beb.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--gIJqy9IJ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/494666/669a1cb1-b348-47fd-aebe-297bb66d2beb.jpeg"
    }
    },
    {
    type_of: "article",
    id: 1088595,
    title: "Writing local rules for ESLint",
    description: "ESLint is a great tool that allowed me to write better code by following the already defined...",
    readable_publish_date: "May 23",
    slug: "writing-local-rules-for-eslint-58bl",
    path: "/jacobandrewsky/writing-local-rules-for-eslint-58bl",
    url: "https://dev.to/jacobandrewsky/writing-local-rules-for-eslint-58bl",
    comments_count: 0,
    public_reactions_count: 7,
    collection_id: 18240,
    published_timestamp: "2022-05-23T13:27:30Z",
    positive_reactions_count: 7,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--NuCJyPD---/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/x1xugklh13dq0f1az7ea.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--jOJ5J5pv--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/x1xugklh13dq0f1az7ea.png",
    canonical_url: "https://dev.to/jacobandrewsky/writing-local-rules-for-eslint-58bl",
    created_at: "2022-05-18T06:46:54Z",
    edited_at: "2022-05-23T13:31:19Z",
    crossposted_at: null,
    published_at: "2022-05-23T13:27:30Z",
    last_comment_at: "2022-05-23T13:27:30Z",
    reading_time_minutes: 4,
    tag_list: [
    "javascript",
    "programming",
    "webdev",
    "beginners"
    ],
    tags: "javascript, programming, webdev, beginners",
    user: {
    name: "Jakub Andrzejewski",
    username: "jacobandrewsky",
    twitter_username: "jacobandrewsky",
    github_username: "Baroshem",
    website_url: "https://pl.linkedin.com/in/jakub-andrzejewski",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--8p-Vfa2M--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/652576/5285632c-5819-4874-adf9-6d3730420830.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--a7o_PXrk--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/652576/5285632c-5819-4874-adf9-6d3730420830.jpeg"
    }
    },
    {
    type_of: "article",
    id: 1093374,
    title: "Lambda Expressions in Java",
    description: "In Java, we all know we can pass data as arguments, but what about passing functionality as an...",
    readable_publish_date: "May 23",
    slug: "lambda-expressions-in-java-2b0c",
    path: "/rishikrishna_r/lambda-expressions-in-java-2b0c",
    url: "https://dev.to/rishikrishna_r/lambda-expressions-in-java-2b0c",
    comments_count: 0,
    public_reactions_count: 7,
    collection_id: null,
    published_timestamp: "2022-05-23T12:42:40Z",
    positive_reactions_count: 7,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1093374.png",
    canonical_url: "https://dev.to/rishikrishna_r/lambda-expressions-in-java-2b0c",
    created_at: "2022-05-23T10:45:37Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-23T12:42:40Z",
    last_comment_at: "2022-05-23T12:42:40Z",
    reading_time_minutes: 3,
    tag_list: [
    "programming",
    "tutorial",
    "java",
    "productivity"
    ],
    tags: "programming, tutorial, java, productivity",
    user: {
    name: "Rishikrishna",
    username: "rishikrishna_r",
    twitter_username: "rishikrishna_r",
    github_username: "rishi1011",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--mTQzA2mw--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/779650/8552fd51-a1e6-4a57-ae3d-f509260cff15.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--1zhYhDxE--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/779650/8552fd51-a1e6-4a57-ae3d-f509260cff15.jpg"
    }
    },
    {
    type_of: "article",
    id: 1093370,
    title: "What was the first project that you did?",
    description: "What was the first project that you did? And what frameworks, languages, and libraries did you use?...",
    readable_publish_date: "May 23",
    slug: "what-was-the-first-project-that-you-did-47no",
    path: "/naddurkostia/what-was-the-first-project-that-you-did-47no",
    url: "https://dev.to/naddurkostia/what-was-the-first-project-that-you-did-47no",
    comments_count: 0,
    public_reactions_count: 4,
    collection_id: null,
    published_timestamp: "2022-05-23T10:27:07Z",
    positive_reactions_count: 4,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1093370.png",
    canonical_url: "https://dev.to/naddurkostia/what-was-the-first-project-that-you-did-47no",
    created_at: "2022-05-23T10:27:07Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-23T10:27:07Z",
    last_comment_at: "2022-05-23T10:27:07Z",
    reading_time_minutes: 1,
    tag_list: [
    "webdev",
    "discuss",
    "programming"
    ],
    tags: "webdev, discuss, programming",
    user: {
    name: "Kostaintyn Naddur",
    username: "naddurkostia",
    twitter_username: null,
    github_username: "naddurkostia",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--SrzFeECc--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/865720/af3dc771-b329-4b9b-aa2e-5798d6666c41.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--HSI1gwZv--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/865720/af3dc771-b329-4b9b-aa2e-5798d6666c41.png"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1093229,
    title: "Build Things And Learn. How Do You?",
    description: "Whatever keeps you from building something, you better start removing it, because it also keeps you from learning.",
    readable_publish_date: "May 23",
    slug: "build-things-and-learn-how-do-you-4222",
    path: "/postman/build-things-and-learn-how-do-you-4222",
    url: "https://dev.to/postman/build-things-and-learn-how-do-you-4222",
    comments_count: 1,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: "2022-05-23T08:41:49Z",
    positive_reactions_count: 5,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--PvpWwMxZ--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/oy48tnvek3oraz392xy1.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--hE6-tpeU--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/oy48tnvek3oraz392xy1.png",
    canonical_url: "https://dev.to/postman/build-things-and-learn-how-do-you-4222",
    created_at: "2022-05-23T08:08:03Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-23T08:41:49Z",
    last_comment_at: "2022-05-23T14:03:46Z",
    reading_time_minutes: 1,
    tag_list: [
    "productivity",
    "discuss",
    "beginners",
    "api"
    ],
    tags: "productivity, discuss, beginners, api",
    user: {
    name: "Jan Schenk (he/him)",
    username: "jansche",
    twitter_username: "jansche",
    github_username: null,
    website_url: "https://t1dcyb.org",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--heP_r9ur--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/28276/cac7a27e-9ee1-4483-88c5-dc6e98365ba0.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--MIf5_c5V--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/28276/cac7a27e-9ee1-4483-88c5-dc6e98365ba0.jpeg"
    },
    organization: {
    name: "Postman",
    username: "postman",
    slug: "postman",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--BWDZkUDQ--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/5035/4c8067b5-61cc-47b4-bf95-8577d10176ee.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--uUdfJDri--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/5035/4c8067b5-61cc-47b4-bf95-8577d10176ee.png"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1093035,
    title: "Basic PostgreSQL on the Command Line",
    description: "I started working through freeCodeCamp's beta curriculum for Relational Database. I like to have a...",
    readable_publish_date: "May 23",
    slug: "basic-postgresql-on-the-command-line-a17",
    path: "/kristenkinnearohlmann/basic-postgresql-on-the-command-line-a17",
    url: "https://dev.to/kristenkinnearohlmann/basic-postgresql-on-the-command-line-a17",
    comments_count: 2,
    public_reactions_count: 11,
    collection_id: null,
    published_timestamp: "2022-05-23T02:47:14Z",
    positive_reactions_count: 11,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--V04blzJR--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/w355kq5zjq1s94an39e3.jpg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--lqSY30JQ--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/w355kq5zjq1s94an39e3.jpg",
    canonical_url: "https://kristenkinnearohlmann.dev/basic-psql/",
    created_at: "2022-05-23T02:47:14Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-23T02:47:14Z",
    last_comment_at: "2022-05-23T08:41:59Z",
    reading_time_minutes: 3,
    tag_list: [
    "postgres",
    "tutorial",
    "linux"
    ],
    tags: "postgres, tutorial, linux",
    user: {
    name: "Kristen Kinnear-Ohlmann",
    username: "kristenkinnearohlmann",
    twitter_username: "kinnear_ohlmann",
    github_username: "kristenkinnearohlmann",
    website_url: "https://kristenkinnearohlmann.dev/",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--o6IaSmUP--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/236415/e8c3af61-e627-4147-a38b-cc735ec2e5d3.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--GMCQ_bLU--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/236415/e8c3af61-e627-4147-a38b-cc735ec2e5d3.png"
    }
    },
    {
    type_of: "article",
    id: 1093034,
    title: "The best ide is..",
    description: "Microsoft word. We all know that is the best ide. I mean which other IDE let's you code in the best...",
    readable_publish_date: "May 23",
    slug: "the-best-ide-is-4294",
    path: "/error434/the-best-ide-is-4294",
    url: "https://dev.to/error434/the-best-ide-is-4294",
    comments_count: 4,
    public_reactions_count: 9,
    collection_id: null,
    published_timestamp: "2022-05-23T02:39:10Z",
    positive_reactions_count: 9,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1093034.png",
    canonical_url: "https://dev.to/error434/the-best-ide-is-4294",
    created_at: "2022-05-23T02:39:10Z",
    edited_at: "2022-05-23T02:41:14Z",
    crossposted_at: null,
    published_at: "2022-05-23T02:39:10Z",
    last_comment_at: "2022-05-23T14:26:03Z",
    reading_time_minutes: 1,
    tag_list: [
    "productivity",
    "programming",
    "discuss",
    "vscode"
    ],
    tags: "productivity, programming, discuss, vscode",
    user: {
    name: "error434",
    username: "error434",
    twitter_username: null,
    github_username: "error434",
    website_url: "https://error434.xyz",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--2vaXOdqI--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/863643/0e52dab7-80df-4554-8231-4647b76820ab.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--pYol-Fxw--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/863643/0e52dab7-80df-4554-8231-4647b76820ab.png"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1092708,
    title: "Pitch me on C++",
    description: "Continuing the series! Feel welcome to dip in and weigh in on a past question. Let's say I've never...",
    readable_publish_date: "May 22",
    slug: "pitch-me-on-c-456j",
    path: "/ben/pitch-me-on-c-456j",
    url: "https://dev.to/ben/pitch-me-on-c-456j",
    comments_count: 18,
    public_reactions_count: 30,
    collection_id: 18125,
    published_timestamp: "2022-05-22T13:40:11Z",
    positive_reactions_count: 30,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--nHN2c2tp--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/lm8wn6bwjtibldnp41wb.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--T8MlbvyO--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/lm8wn6bwjtibldnp41wb.png",
    canonical_url: "https://dev.to/ben/pitch-me-on-c-456j",
    created_at: "2022-05-22T13:40:11Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-22T13:40:11Z",
    last_comment_at: "2022-05-23T13:35:05Z",
    reading_time_minutes: 1,
    tag_list: [
    "cpp",
    "discuss",
    "pitchme"
    ],
    tags: "cpp, discuss, pitchme",
    user: {
    name: "Ben Halpern",
    username: "ben",
    twitter_username: "bendhalpern",
    github_username: "benhalpern",
    website_url: "http://benhalpern.com",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--nz-jndal--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/1/f451a206-11c8-4e3d-8936-143d0a7e65bb.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--Ea1OGrCb--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/1/f451a206-11c8-4e3d-8936-143d0a7e65bb.png"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1092585,
    title: "[DISCUSSION] What is your perfect work environment ?",
    description: "Comment below your must have factors for a perfect work environment",
    readable_publish_date: "May 22",
    slug: "discussion-what-is-your-perfect-work-environment--1hkl",
    path: "/zabdeldjallil/discussion-what-is-your-perfect-work-environment--1hkl",
    url: "https://dev.to/zabdeldjallil/discussion-what-is-your-perfect-work-environment--1hkl",
    comments_count: 10,
    public_reactions_count: 7,
    collection_id: null,
    published_timestamp: "2022-05-22T11:06:12Z",
    positive_reactions_count: 7,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1092585.png",
    canonical_url: "https://dev.to/zabdeldjallil/discussion-what-is-your-perfect-work-environment--1hkl",
    created_at: "2022-05-22T11:06:12Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-22T11:06:12Z",
    last_comment_at: "2022-05-23T11:47:23Z",
    reading_time_minutes: 1,
    tag_list: [
    "os",
    "webdev",
    "programming",
    "productivity"
    ],
    tags: "os, webdev, programming, productivity",
    user: {
    name: "Zitouni Abdeldjallil",
    username: "zabdeldjallil",
    twitter_username: null,
    github_username: "Zabdeldjallil",
    website_url: "https://github.com/Zabdeldjallil",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--cjdDJ1Hw--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/540462/ebfd2272-c202-46a6-adcc-4e9c149ead60.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--AqEbWIzw--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/540462/ebfd2272-c202-46a6-adcc-4e9c149ead60.jpeg"
    }
    },
    {
    type_of: "article",
    id: 1093010,
    title: "What tools do you use?",
    description: "This is a series leading up to a Virtual Coffee Lunch &amp; Learn titled Asking Coding Questions with...",
    readable_publish_date: "May 23",
    slug: "what-tools-do-you-use-785",
    path: "/virtualcoffee/what-tools-do-you-use-785",
    url: "https://dev.to/virtualcoffee/what-tools-do-you-use-785",
    comments_count: 2,
    public_reactions_count: 14,
    collection_id: 18232,
    published_timestamp: "2022-05-23T00:56:22Z",
    positive_reactions_count: 14,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--pdJaAric--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/jhu562c4ju7618mxrbty.jpeg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--YkWgk1DI--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/jhu562c4ju7618mxrbty.jpeg",
    canonical_url: "https://dev.to/virtualcoffee/what-tools-do-you-use-785",
    created_at: "2022-05-23T00:31:10Z",
    edited_at: "2022-05-23T01:01:57Z",
    crossposted_at: null,
    published_at: "2022-05-23T00:56:22Z",
    last_comment_at: "2022-05-23T14:28:45Z",
    reading_time_minutes: 1,
    tag_list: [
    "discuss",
    "tooling",
    "productivity"
    ],
    tags: "discuss, tooling, productivity",
    user: {
    name: "Nick Taylor (he/him)",
    username: "nickytonline",
    twitter_username: "nickytonline",
    github_username: "nickytonline",
    website_url: "https://timeline.iamdeveloper.com",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--T9un0IK7--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/9597/2629be65-f045-4612-a7e9-28cd9e48bd49.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--h-JUieId--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/9597/2629be65-f045-4612-a7e9-28cd9e48bd49.jpg"
    },
    organization: {
    name: "Virtual Coffee",
    username: "virtualcoffee",
    slug: "virtualcoffee",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--lHykUh8R--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/3610/42d75122-d731-47ba-9473-cf192c6293a6.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--20QiT3Ys--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/3610/42d75122-d731-47ba-9473-cf192c6293a6.png"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1091804,
    title: "[CSS design] I think about specifying z-index difficult to break",
    description: "Summary Defines the z-index value to be specified for each component. ...",
    readable_publish_date: "May 22",
    slug: "css-design-i-think-about-specifying-z-index-difficult-to-break-1koi",
    path: "/hiro0218/css-design-i-think-about-specifying-z-index-difficult-to-break-1koi",
    url: "https://dev.to/hiro0218/css-design-i-think-about-specifying-z-index-difficult-to-break-1koi",
    comments_count: 2,
    public_reactions_count: 10,
    collection_id: null,
    published_timestamp: "2022-05-22T14:47:04Z",
    positive_reactions_count: 10,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1091804.png",
    canonical_url: "https://dev.to/hiro0218/css-design-i-think-about-specifying-z-index-difficult-to-break-1koi",
    created_at: "2022-05-21T07:12:43Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-22T14:47:04Z",
    last_comment_at: "2022-05-23T12:16:53Z",
    reading_time_minutes: 2,
    tag_list: [
    "css",
    "design"
    ],
    tags: "css, design",
    user: {
    name: "hiro",
    username: "hiro0218",
    twitter_username: "hiro0218",
    github_username: "hiro0218",
    website_url: "https://b.0218.jp/",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--3OugRheO--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/41515/73afe581-dd5d-4747-977e-b69c3666a0a5.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--xeMzykuh--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/41515/73afe581-dd5d-4747-977e-b69c3666a0a5.png"
    }
    },
    {
    type_of: "article",
    id: 1092606,
    title: "As a developer, I love ... ?",
    description: "As a developer what you love?",
    readable_publish_date: "May 22",
    slug: "as-a-developer-i-love--1e72",
    path: "/soniarpit/as-a-developer-i-love--1e72",
    url: "https://dev.to/soniarpit/as-a-developer-i-love--1e72",
    comments_count: 10,
    public_reactions_count: 6,
    collection_id: null,
    published_timestamp: "2022-05-22T12:19:08Z",
    positive_reactions_count: 6,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--S8lC2sfv--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/1lx1ls7cqv6ecs8pxdy5.jpg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--TvTzfNFB--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/1lx1ls7cqv6ecs8pxdy5.jpg",
    canonical_url: "https://dev.to/soniarpit/as-a-developer-i-love--1e72",
    created_at: "2022-05-22T12:19:08Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-22T12:19:08Z",
    last_comment_at: "2022-05-23T13:15:02Z",
    reading_time_minutes: 1,
    tag_list: [
    "discuss"
    ],
    tags: "discuss",
    user: {
    name: "Arpit",
    username: "soniarpit",
    twitter_username: "awwarpit",
    github_username: "SoniArpit",
    website_url: "https://www.codesnail.com/",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--VfWJ8_rD--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/385896/91cf1377-d582-43d6-82d2-167ba1b36594.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--0Xh8rs9G--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/385896/91cf1377-d582-43d6-82d2-167ba1b36594.jpg"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1089024,
    title: "SWAHILI TEXT AUGMENTATION WITH BACK TRANSLATION",
    description: "Data is a tool for enhancing intuitions ~ Hilary Mason data scientist and founder of Fast Forward...",
    readable_publish_date: "May 18",
    slug: "swahili-text-augmentation-with-back-translation-2o5g",
    path: "/neurotech_africa/swahili-text-augmentation-with-back-translation-2o5g",
    url: "https://dev.to/neurotech_africa/swahili-text-augmentation-with-back-translation-2o5g",
    comments_count: 0,
    public_reactions_count: 6,
    collection_id: null,
    published_timestamp: "2022-05-18T15:09:35Z",
    positive_reactions_count: 6,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--hKTR0flE--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/tq02xlhead3grsirzujz.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--_rltd2zA--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/tq02xlhead3grsirzujz.png",
    canonical_url: "https://dev.to/neurotech_africa/swahili-text-augmentation-with-back-translation-2o5g",
    created_at: "2022-05-18T15:09:35Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-18T15:09:35Z",
    last_comment_at: "2022-05-18T15:09:35Z",
    reading_time_minutes: 5,
    tag_list: [ ],
    tags: "",
    user: {
    name: "Anthony Mipawa",
    username: "tonyloyt",
    twitter_username: null,
    github_username: "Tonyloyt",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--4OoNj5Cc--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/556970/b3bc9b05-1dfd-4924-a080-d32b76bc583a.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--HPJNNoKf--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/556970/b3bc9b05-1dfd-4924-a080-d32b76bc583a.jpg"
    },
    organization: {
    name: "NEUROTECH AFRICA",
    username: "neurotech_africa",
    slug: "neurotech_africa",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--wsr3dZD4--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/5628/67456138-0eec-4808-baf8-540aa5250776.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--FG9trDfh--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/5628/67456138-0eec-4808-baf8-540aa5250776.jpg"
    }
    },
    {
    type_of: "article",
    id: 1088987,
    title: "The importance of confusion matrix in machine learning",
    description: "As a machine learning engineer, it is important to know how well our model performs on our...",
    readable_publish_date: "May 18",
    slug: "the-importance-of-confusion-matrix-in-machine-learning-nca",
    path: "/joy_chiorlu/the-importance-of-confusion-matrix-in-machine-learning-nca",
    url: "https://dev.to/joy_chiorlu/the-importance-of-confusion-matrix-in-machine-learning-nca",
    comments_count: 0,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: "2022-05-18T13:45:50Z",
    positive_reactions_count: 5,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1088987.png",
    canonical_url: "https://dev.to/joy_chiorlu/the-importance-of-confusion-matrix-in-machine-learning-nca",
    created_at: "2022-05-18T13:45:50Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-18T13:45:50Z",
    last_comment_at: "2022-05-18T13:45:50Z",
    reading_time_minutes: 4,
    tag_list: [ ],
    tags: "",
    user: {
    name: "Sarima Chiorlu",
    username: "joy_chiorlu",
    twitter_username: "joy_chiorlu",
    github_username: "Richiio",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--zIQlvn3f--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/588480/eaf48b4f-9d58-4634-9114-6ea34dceffb9.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--Dbe2Yz6t--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/588480/eaf48b4f-9d58-4634-9114-6ea34dceffb9.png"
    }
    },
    {
    type_of: "article",
    id: 1092902,
    title: "Sell me on Turborepo",
    description: "A post by Darren Baldwin",
    readable_publish_date: "May 22",
    slug: "sell-me-on-turbo-repo-4i0h",
    path: "/codemaster747/sell-me-on-turbo-repo-4i0h",
    url: "https://dev.to/codemaster747/sell-me-on-turbo-repo-4i0h",
    comments_count: 0,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: "2022-05-22T18:54:30Z",
    positive_reactions_count: 5,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1092902.png",
    canonical_url: "https://dev.to/codemaster747/sell-me-on-turbo-repo-4i0h",
    created_at: "2022-05-22T18:54:30Z",
    edited_at: "2022-05-22T18:54:55Z",
    crossposted_at: null,
    published_at: "2022-05-22T18:54:30Z",
    last_comment_at: "2022-05-22T18:54:30Z",
    reading_time_minutes: 0,
    tag_list: [
    "discuss",
    "webdev",
    "github"
    ],
    tags: "discuss, webdev, github",
    user: {
    name: "Darren Baldwin",
    username: "codemaster747",
    twitter_username: "CodeMaster747",
    github_username: "Devd0",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--Luf0wflc--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/719820/b9c71f4a-243c-4367-ac58-70ab3c4f310a.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--T9bIIW__--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/719820/b9c71f4a-243c-4367-ac58-70ab3c4f310a.jpg"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1092166,
    title: "Why We Hate…",
    description: "Original post in Kodumaro. Sometimes I spend some time trying to acquire new programming skills,...",
    readable_publish_date: "May 21",
    slug: "why-we-hate-3m8k",
    path: "/cacilhas/why-we-hate-3m8k",
    url: "https://dev.to/cacilhas/why-we-hate-3m8k",
    comments_count: 9,
    public_reactions_count: 15,
    collection_id: null,
    published_timestamp: "2022-05-21T19:16:38Z",
    positive_reactions_count: 15,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--X_1qtxLm--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/x2rk7rjrnq679lqpwv4n.jpg",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--Mw3KlGqV--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/x2rk7rjrnq679lqpwv4n.jpg",
    canonical_url: "https://dev.to/cacilhas/why-we-hate-3m8k",
    created_at: "2022-05-21T19:16:38Z",
    edited_at: "2022-05-21T22:45:32Z",
    crossposted_at: null,
    published_at: "2022-05-21T19:16:38Z",
    last_comment_at: "2022-05-22T19:58:34Z",
    reading_time_minutes: 4,
    tag_list: [
    "career",
    "culture"
    ],
    tags: "career, culture",
    user: {
    name: "Arĥimedeς ℳontegasppα ℭacilhας",
    username: "cacilhas",
    twitter_username: "montegasppa",
    github_username: "cacilhas",
    website_url: "https://kodumaro.cacilhas.info/",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--1FfyCHyE--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/423224/24661fdf-6ea5-479a-a287-05068ed2f5b7.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--2S4kuCvQ--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/423224/24661fdf-6ea5-479a-a287-05068ed2f5b7.png"
    }
    },
    {
    type_of: "article",
    id: 1092765,
    title: "What pet projects are you working on, just for fun?",
    description: "Could be anything, even non-technical. I like to tinker with bicycles (I've built and rebuilt a few...",
    readable_publish_date: "May 22",
    slug: "what-pet-projects-are-you-working-on-just-for-fun-29ek",
    path: "/paddyredbeard/what-pet-projects-are-you-working-on-just-for-fun-29ek",
    url: "https://dev.to/paddyredbeard/what-pet-projects-are-you-working-on-just-for-fun-29ek",
    comments_count: 0,
    public_reactions_count: 6,
    collection_id: null,
    published_timestamp: "2022-05-22T16:17:02Z",
    positive_reactions_count: 6,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1092765.png",
    canonical_url: "https://dev.to/paddyredbeard/what-pet-projects-are-you-working-on-just-for-fun-29ek",
    created_at: "2022-05-22T16:17:02Z",
    edited_at: "2022-05-22T16:31:13Z",
    crossposted_at: null,
    published_at: "2022-05-22T16:17:02Z",
    last_comment_at: "2022-05-22T16:17:02Z",
    reading_time_minutes: 1,
    tag_list: [
    "fun",
    "petproject",
    "watercooler"
    ],
    tags: "fun, petproject, watercooler",
    user: {
    name: "Patrick B",
    username: "paddyredbeard",
    twitter_username: null,
    github_username: "paddyredbeard",
    website_url: "https://pddyrdbrd.net/",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--W3QGRNkS--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/860981/d1c77d10-0924-4f4d-9fd6-4cb9cbcb86d7.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--VO4lREJ9--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/860981/d1c77d10-0924-4f4d-9fd6-4cb9cbcb86d7.jpeg"
    },
    flare_tag: {
    name: "watercooler",
    bg_color_hex: "#D0ECFF",
    text_color_hex: "#130074"
    }
    },
    {
    type_of: "article",
    id: 1089210,
    title: "DIFT: Dozen Issues for First Timers",
    description: "It's like Hacktoberfest, but not in October!",
    readable_publish_date: "May 18",
    slug: "dift-dozen-issues-for-first-timers-50em",
    path: "/amplication/dift-dozen-issues-for-first-timers-50em",
    url: "https://dev.to/amplication/dift-dozen-issues-for-first-timers-50em",
    comments_count: 0,
    public_reactions_count: 2,
    collection_id: null,
    published_timestamp: "2022-05-18T18:44:42Z",
    positive_reactions_count: 2,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--nvoeICO5--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/829997m9rkt52xefu0lm.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--XGT9Jhm1--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/829997m9rkt52xefu0lm.png",
    canonical_url: "https://dev.to/amplication/dift-dozen-issues-for-first-timers-50em",
    created_at: "2022-05-18T18:44:42Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-18T18:44:42Z",
    last_comment_at: "2022-05-18T18:44:42Z",
    reading_time_minutes: 1,
    tag_list: [
    "beginners",
    "node",
    "contributorswanted",
    "opensource"
    ],
    tags: "beginners, node, contributorswanted, opensource",
    user: {
    name: "Michael Solati",
    username: "michaelsolati",
    twitter_username: "MichaelSolati",
    github_username: "MichaelSolati",
    website_url: "https://michaelsolati.com/",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--gDjrpo7F--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/2585/712e1551-ecda-443f-9bf2-2082b7a8b49e.jpg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--Q9YL7TKT--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/2585/712e1551-ecda-443f-9bf2-2082b7a8b49e.jpg"
    },
    organization: {
    name: "Amplication",
    username: "amplication",
    slug: "amplication",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--2mqROtZz--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/4777/96ce735e-6864-418f-9ebd-4cd09e115d7d.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--VTMuFj-_--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/4777/96ce735e-6864-418f-9ebd-4cd09e115d7d.png"
    }
    },
    {
    type_of: "article",
    id: 1090965,
    title: 'What is the most readable programming language in your opinion?',
    description: "Maybe it's not the best tool for certain because it is slow, or lacks certain features you care about...",
    readable_publish_date: "May 20",
    slug: "what-is-the-most-readable-programming-language-in-your-opinion-f3",
    path: "/brunoj/what-is-the-most-readable-programming-language-in-your-opinion-f3",
    url: "https://dev.to/brunoj/what-is-the-most-readable-programming-language-in-your-opinion-f3",
    comments_count: 8,
    public_reactions_count: 8,
    collection_id: null,
    published_timestamp: "2022-05-20T14:08:14Z",
    positive_reactions_count: 8,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1090965.png",
    canonical_url: "https://dev.to/brunoj/what-is-the-most-readable-programming-language-in-your-opinion-f3",
    created_at: "2022-05-20T14:08:14Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-20T14:08:14Z",
    last_comment_at: "2022-05-21T12:42:50Z",
    reading_time_minutes: 1,
    tag_list: [
    "discuss"
    ],
    tags: "discuss",
    user: {
    name: "Bruno",
    username: "brunoj",
    twitter_username: null,
    github_username: null,
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--tWHlCiBi--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/799003/52075027-4445-4237-8edc-c17ec6f44dac.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--yFhQtvGj--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/799003/52075027-4445-4237-8edc-c17ec6f44dac.jpeg"
    },
    flare_tag: {
    name: "discuss",
    bg_color_hex: "#1ad643",
    text_color_hex: "#FFFFFF"
    }
    },
    {
    type_of: "article",
    id: 1090917,
    title: "Resumão de Python para iniciantes com aulas! [PT-BR]",
    description: "EPTA-Forge-Python Aqui vai ficar o resumão do curso! Links: Aula 1 Aula 2 Aula 3 Replit...",
    readable_publish_date: "May 20",
    slug: "resumao-de-python-para-iniciantes-com-aulas-pt-br-1lmm",
    path: "/llxd/resumao-de-python-para-iniciantes-com-aulas-pt-br-1lmm",
    url: "https://dev.to/llxd/resumao-de-python-para-iniciantes-com-aulas-pt-br-1lmm",
    comments_count: 0,
    public_reactions_count: 10,
    collection_id: null,
    published_timestamp: "2022-05-20T12:04:26Z",
    positive_reactions_count: 10,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--hGKCFrsW--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/d7rz8hbt1raegau03d4i.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--rsV2c3ah--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/d7rz8hbt1raegau03d4i.png",
    canonical_url: "https://dev.to/llxd/resumao-de-python-para-iniciantes-com-aulas-pt-br-1lmm",
    created_at: "2022-05-20T12:04:26Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-20T12:04:26Z",
    last_comment_at: "2022-05-20T12:04:26Z",
    reading_time_minutes: 6,
    tag_list: [
    "python",
    "braziliandevs",
    "beginners",
    "tutorial"
    ],
    tags: "python, braziliandevs, beginners, tutorial",
    user: {
    name: "Lucas Lima do Nascimento",
    username: "llxd",
    twitter_username: null,
    github_username: "LLxD",
    website_url: "https://llxd.tk",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--N4XVQbNT--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/527863/d55a08bc-10ad-4e64-96ff-f88d5b477c8f.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--Evd8ceHz--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/527863/d55a08bc-10ad-4e64-96ff-f88d5b477c8f.png"
    }
    },
    {
    type_of: "article",
    id: 1090842,
    title: "Interested in weekend project?",
    description: "I have a simple project to work on this weekend. Just to brief.. A chrome extension that shows data...",
    readable_publish_date: "May 20",
    slug: "anyone-interested-in-weekend-project-ec0",
    path: "/ml318097/anyone-interested-in-weekend-project-ec0",
    url: "https://dev.to/ml318097/anyone-interested-in-weekend-project-ec0",
    comments_count: 0,
    public_reactions_count: 1,
    collection_id: null,
    published_timestamp: "2022-05-20T10:47:17Z",
    positive_reactions_count: 1,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1090842.png",
    canonical_url: "https://dev.to/ml318097/anyone-interested-in-weekend-project-ec0",
    created_at: "2022-05-20T10:47:17Z",
    edited_at: "2022-05-20T10:47:37Z",
    crossposted_at: null,
    published_at: "2022-05-20T10:47:17Z",
    last_comment_at: "2022-05-20T10:47:17Z",
    reading_time_minutes: 1,
    tag_list: [
    "help",
    "webdev",
    "discuss"
    ],
    tags: "help, webdev, discuss",
    user: {
    name: "Mehul Lakhanpal",
    username: "ml318097",
    twitter_username: "318097",
    github_username: "318097",
    website_url: "https://www.codedrops.tech",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--F3nalc_R--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/158733/7c3cc61d-12b7-496a-9dc1-e14024b5702b.png",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--RREWgy64--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/158733/7c3cc61d-12b7-496a-9dc1-e14024b5702b.png"
    },
    flare_tag: {
    name: "help",
    bg_color_hex: "#ff3232",
    text_color_hex: "#ffffff"
    }
    },
    {
    type_of: "article",
    id: 1090084,
    title: "Global Accessbility Awareness Day - Does your web product support the needs of the many?",
    description: "You never create one product on the web - you create a product that people can change to their needs. At least you should.",
    readable_publish_date: "May 19",
    slug: "global-accessbility-awareness-day-does-your-web-product-support-the-needs-of-the-many-4pe",
    path: "/codepo8/global-accessbility-awareness-day-does-your-web-product-support-the-needs-of-the-many-4pe",
    url: "https://dev.to/codepo8/global-accessbility-awareness-day-does-your-web-product-support-the-needs-of-the-many-4pe",
    comments_count: 0,
    public_reactions_count: 19,
    collection_id: null,
    published_timestamp: "2022-05-19T17:03:09Z",
    positive_reactions_count: 19,
    cover_image: null,
    social_image: "https://dev.to/social_previews/article/1090084.png",
    canonical_url: "https://dev.to/codepo8/global-accessbility-awareness-day-does-your-web-product-support-the-needs-of-the-many-4pe",
    created_at: "2022-05-19T17:03:09Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-19T17:03:09Z",
    last_comment_at: "2022-05-19T17:03:09Z",
    reading_time_minutes: 3,
    tag_list: [
    "gaad",
    "tooling",
    "emulation"
    ],
    tags: "gaad, tooling, emulation",
    user: {
    name: "Christian Heilmann",
    username: "codepo8",
    twitter_username: "codepo8",
    github_username: "codepo8",
    website_url: "https://christianheilmann.com",
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--unYphkuQ--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/110884/c4807448-b7fe-4d8d-ba13-a3ec4c97b377.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--6g52Nrx9--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/110884/c4807448-b7fe-4d8d-ba13-a3ec4c97b377.jpeg"
    }
    },
    {
    type_of: "article",
    id: 1090910,
    title: "JavaScript Theme Toggle.",
    description: "Hello there, pals. Hello and thank you for visiting my blog. We're going to build a theme toggle...",
    readable_publish_date: "May 20",
    slug: "javascript-theme-toggle-5hdj",
    path: "/jovickcoder/javascript-theme-toggle-5hdj",
    url: "https://dev.to/jovickcoder/javascript-theme-toggle-5hdj",
    comments_count: 0,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: "2022-05-20T12:33:16Z",
    positive_reactions_count: 5,
    cover_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--FXISJqP3--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/rg1a00l4lioijzyq0i3f.png",
    social_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--z2b-KizP--/c_imagga_scale,f_auto,fl_progressive,h_500,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/rg1a00l4lioijzyq0i3f.png",
    canonical_url: "https://dev.to/jovickcoder/javascript-theme-toggle-5hdj",
    created_at: "2022-05-20T11:49:35Z",
    edited_at: null,
    crossposted_at: null,
    published_at: "2022-05-20T12:33:16Z",
    last_comment_at: "2022-05-20T12:33:16Z",
    reading_time_minutes: 6,
    tag_list: [
    "javascript",
    "html",
    "css"
    ],
    tags: "javascript, html, css",
    user: {
    name: "Josiah Victor",
    username: "jovickcoder",
    twitter_username: null,
    github_username: "jovick-coder",
    website_url: null,
    profile_image: "https://res.cloudinary.com/practicaldev/image/fetch/s--FJo9r5FO--/c_fill,f_auto,fl_progressive,h_640,q_auto,w_640/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/622002/3603d05b-4813-4d21-84d1-1d80e3c4c997.jpeg",
    profile_image_90: "https://res.cloudinary.com/practicaldev/image/fetch/s--KmIvctS_--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/622002/3603d05b-4813-4d21-84d1-1d80e3c4c997.jpeg"
    }
    }
    ]
export default posts